apiVersion: v1
kind: ConfigMap
metadata:
  name: splunk-hec-config
  namespace: monitoring
  labels:
    app: kubewatch
data:
  SPLUNK_HEC_HOST: splunk-hec-service.monitoring
  SPLUNK_HEC_PORT: '8088'
  SPLUNK_HOST: <enter the desired name>
  SPLUNK_INDEX: 'default'
  SPLUNK_SOURCE: 'kubewatch'
  SPLUNK_SOURCETYPE: 'kubewatch'
